from .qsnet.qsnet import Net as QSNet
from .qsnet.QSNetDataSourceDelegate import QSNetDataSourceDelegate as QSNetDataSourceDelegate
from .qsnet.QSNetTrainerDelegate import QSNetTrainerDelegate as QSNetTrainerDelegate
from .qsnet.QSNetEvaluationDelegate import QSNetEvaluationDelegate as QSNetEvaluationDelegate
from .qsnet.QSNetResultDelegate import QSNetResultDelegate as QSNetResultDelegate

from .densenet.densenet import DenseNet
from .densenet.DenseNetDataSourceDelegate import DenseNetDataSourceDelegate as DenseNetDataSourceDelegate
from .densenet.DenseNetTrainerDelegate import DenseNetTrainerDelegate as DenseNetTrainerDelegate
from .densenet.DenseNetEvaluationDelegate import DenseNetEvaluationDelegate as DenseNetEvaluationDelegate
